//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_OutListItems
    {
        public int OID { get; set; }
        public string pre_entry { get; set; }
        public string g_no { get; set; }
        public string clpno { get; set; }
        public string oseq { get; set; }
    }
}
