//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class bookingDtl
	{
		public bookingDtl ToPOCO(bool isPOCO = true){
			return new bookingDtl(){
				dID = this.dID,
				hID = this.hID,
				so_no = this.so_no,
				orderNum = this.orderNum,
				po = this.po,
				sku = this.sku,
				Marks = this.Marks,
				CTN = this.CTN,
				PCS = this.PCS,
				ProductName = this.ProductName,
				GrossWeight = this.GrossWeight,
				CBM = this.CBM,
				Remark = this.Remark,
				ItemNo = this.ItemNo,
				CustomerMaterialNo = this.CustomerMaterialNo,
				SalesMaterial = this.SalesMaterial,
				Material = this.Material,
				SalesOrd = this.SalesOrd,
				Client = this.Client,
			};
		}
	}
}
