//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class BookingHeadEdi
	{
		public BookingHeadEdi ToPOCO(bool isPOCO = true){
			return new BookingHeadEdi(){
				so_no = this.so_no,
				input_time = this.input_time,
				shipper_ref = this.shipper_ref,
				vessel = this.vessel,
				voyage = this.voyage,
				POD = this.POD,
				dest_code = this.dest_code,
				dest = this.dest,
				consg_code = this.consg_code,
				totqty = this.totqty,
				totweight = this.totweight,
				totcbm = this.totcbm,
				totpcs = this.totpcs,
				rec_totqty = this.rec_totqty,
				rec_totweight = this.rec_totweight,
				rec_totcbm = this.rec_totcbm,
				rec_totpcs = this.rec_totpcs,
				rec_date = this.rec_date,
				EDI_Status = this.EDI_Status,
				EDIFile_In = this.EDIFile_In,
				EDIFile_Out = this.EDIFile_Out,
				EDI_Account = this.EDI_Account,
				XFactory_Date = this.XFactory_Date,
				NLT = this.NLT,
				Ship_To_Name = this.Ship_To_Name,
				vendor = this.vendor,
			};
		}
	}
}
