//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class bookingVendor
	{
		public bookingVendor ToPOCO(bool isPOCO = true){
			return new bookingVendor(){
				vendor_code = this.vendor_code,
				vendor_name = this.vendor_name,
				vendor_contact = this.vendor_contact,
				vendor_address = this.vendor_address,
				vendor_email = this.vendor_email,
				vendor_fax = this.vendor_fax,
				wh_id = this.wh_id,
				forward_code = this.forward_code,
				telNo = this.telNo,
				consignee = this.consignee,
				notifyconsignee = this.notifyconsignee,
				secondnotifyconsignee = this.secondnotifyconsignee,
				consigneetel = this.consigneetel,
				notifyconsigneetel = this.notifyconsigneetel,
				secondnotifyconsigneetel = this.secondnotifyconsigneetel,
			};
		}
	}
}
