//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class collectlist
	{
		public collectlist ToPOCO(bool isPOCO = true){
			return new collectlist(){
				customer = this.customer,
				consg_code = this.consg_code,
				collectdate = this.collectdate,
				rec_qty = this.rec_qty,
				rec_cbm = this.rec_cbm,
				load_qty = this.load_qty,
				load_cbm = this.load_cbm,
				qtybal = this.qtybal,
				cbmbal = this.cbmbal,
			};
		}
	}
}
