//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class customer1
	{
		public customer1 ToPOCO(bool isPOCO = true){
			return new customer1(){
				id = this.id,
				cust_name = this.cust_name,
				address1 = this.address1,
				tel = this.tel,
				fax = this.fax,
				cust_email = this.cust_email,
				contact = this.contact,
				remark = this.remark,
				SM_Operator = this.SM_Operator,
				SM_email = this.SM_email,
			};
		}
	}
}
