//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Customer_Order
	{
		public Customer_Order ToPOCO(bool isPOCO = true){
			return new Customer_Order(){
				ID = this.ID,
				Vendor = this.Vendor,
				Vendor_Name = this.Vendor_Name,
				ClientCode = this.ClientCode,
				Customer_Name = this.Customer_Name,
				Customer_PO = this.Customer_PO,
				FirstDate = this.FirstDate,
				Cancel_Date = this.Cancel_Date,
				SalesOrderSTO = this.SalesOrderSTO,
				Item_NO = this.Item_NO,
				Customer_Material_Number = this.Customer_Material_Number,
				Sales_Material = this.Sales_Material,
				Material = this.Material,
				Short_text = this.Short_text,
				Delev_Date = this.Delev_Date,
				Item = this.Item,
				Po_Quantity = this.Po_Quantity,
				Total_Carton = this.Total_Carton,
				TotalGrossWeight = this.TotalGrossWeight,
				TotalVolume = this.TotalVolume,
				TotalNetWeight = this.TotalNetWeight,
				ShipTo_City = this.ShipTo_City,
				DestCode = this.DestCode,
				ShipTo_Name = this.ShipTo_Name,
				ShipTo_Country = this.ShipTo_Country,
				Mfr_Country = this.Mfr_Country,
				Mfr_City = this.Mfr_City,
				Line = this.Line,
				GroupNumber = this.GroupNumber,
			};
		}
	}
}
