//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FCR_Detail
	{
		public FCR_Detail ToPOCO(bool isPOCO = true){
			return new FCR_Detail(){
				id = this.id,
				fcr_no = this.fcr_no,
				seq = this.seq,
				clpno = this.clpno,
				cfsso = this.cfsso,
				cont_no = this.cont_no,
				seal_no = this.seal_no,
			};
		}
	}
}
