//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FinalPo_Cancel_Record
	{
		public FinalPo_Cancel_Record ToPOCO(bool isPOCO = true){
			return new FinalPo_Cancel_Record(){
				cID = this.cID,
				pID = this.pID,
				cancel_time = this.cancel_time,
				cancel_user = this.cancel_user,
				release = this.release,
				release_user = this.release_user,
				remark = this.remark,
			};
		}
	}
}
