//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FinalLoadingPlan_Payment
	{
		public FinalLoadingPlan_Payment ToPOCO(bool isPOCO = true){
			return new FinalLoadingPlan_Payment(){
				ID = this.ID,
				JOB_NO = this.JOB_NO,
				Value = this.Value,
				Payment_Date = this.Payment_Date,
				Label_Fee = this.Label_Fee,
				Fwd_INV = this.Fwd_INV,
				Remark = this.Remark,
				Oth_Charge = this.Oth_Charge,
				InvoiceNo = this.InvoiceNo,
			};
		}
	}
}
