//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FinalLoadPlanJobRecord
	{
		public FinalLoadPlanJobRecord ToPOCO(bool isPOCO = true){
			return new FinalLoadPlanJobRecord(){
				jlID = this.jlID,
				JOB_NO = this.JOB_NO,
				Action_Type = this.Action_Type,
				Action_Field = this.Action_Field,
				Remark = this.Remark,
				input_date = this.input_date,
			};
		}
	}
}
