//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class In2So
	{
		public In2So ToPOCO(bool isPOCO = true){
			return new In2So(){
				LinkID = this.LinkID,
				So_No = this.So_No,
				LinkSeq = this.LinkSeq,
				pre_entry = this.pre_entry,
				In_No = this.In_No,
				g_no = this.g_no,
				Seq = this.Seq,
				NewSeq = this.NewSeq,
				Item_No = this.Item_No,
				Pack_No = this.Pack_No,
				PackBal = this.PackBal,
				Spec = this.Spec,
				PCS = this.PCS,
				PCSBal = this.PCSBal,
				Remark = this.Remark,
			};
		}
	}
}
