//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class invoice
	{
		public invoice ToPOCO(bool isPOCO = true){
			return new invoice(){
				iID = this.iID,
				invoiceNo = this.invoiceNo,
				so_no = this.so_no,
				exchange_rate = this.exchange_rate,
				Total_USD = this.Total_USD,
				invoice_date = this.invoice_date,
				rec_date = this.rec_date,
				vendor = this.vendor,
				cbm_price = this.cbm_price,
				cbm = this.cbm,
			};
		}
	}
}
