//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class newpacking
	{
		public newpacking ToPOCO(bool isPOCO = true){
			return new newpacking(){
				so_no = this.so_no,
				newseq = this.newseq,
				qty = this.qty,
				qtybal = this.qtybal,
				pcs = this.pcs,
				pcsbal = this.pcsbal,
				qtyinplt = this.qtyinplt,
				unit = this.unit,
				length = this.length,
				width = this.width,
				height = this.height,
				cbm = this.cbm,
				unitwei = this.unitwei,
				weight = this.weight,
				spec = this.spec,
				repackdate = this.repackdate,
				po = this.po,
				item_no = this.item_no,
				remark = this.remark,
				LinkToIn = this.LinkToIn,
			};
		}
	}
}
