//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class out_head_cy
	{
		public out_head_cy ToPOCO(bool isPOCO = true){
			return new out_head_cy(){
				ID = this.ID,
				la_no = this.la_no,
				cont_no = this.cont_no,
				vessel = this.vessel,
				voyage = this.voyage,
				ETD = this.ETD,
				ETA = this.ETA,
				seal_no = this.seal_no,
				cont_type = this.cont_type,
				POE = this.POE,
				booking_number = this.booking_number,
				destination = this.destination,
				division = this.division,
				total_pcs = this.total_pcs,
				total_ctn = this.total_ctn,
				total_cbm = this.total_cbm,
				total_weight = this.total_weight,
				acceptance = this.acceptance,
				Carrier = this.Carrier,
				MBL = this.MBL,
				HBL = this.HBL,
				FcrData = this.FcrData,
				ECV_Status = this.ECV_Status,
				shipment_id = this.shipment_id,
				Closingdate = this.Closingdate,
			};
		}
	}
}
