//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Outhead
	{
		public Outhead ToPOCO(bool isPOCO = true){
			return new Outhead(){
				ebID = this.ebID,
				pre_entry = this.pre_entry,
				act_date = this.act_date,
				agent_code = this.agent_code,
				agent_name = this.agent_name,
				appl_no = this.appl_no,
				appr_no = this.appr_no,
				bill_no = this.bill_no,
				carbox_no = this.carbox_no,
				cert_mark = this.cert_mark,
				co_owner = this.co_owner,
				contr_no = this.contr_no,
				customs_co = this.customs_co,
				cut_mode = this.cut_mode,
				d_date = this.d_date,
				port_line = this.port_line,
				district_c = this.district_c,
				entry_id = this.entry_id,
				ex_source = this.ex_source,
				factory = this.factory,
				fee_curr = this.fee_curr,
				fee_mark = this.fee_mark,
				fee_rate = this.fee_rate,
				givetax = this.givetax,
				gross_wt = this.gross_wt,
				i_e_date = this.i_e_date,
				i_e_port = this.i_e_port,
				duty_ratio = this.duty_ratio,
				insur_curr = this.insur_curr,
				insur_mark = this.insur_mark,
				insur_rate = this.insur_rate,
				items_no = this.items_no,
				license_no = this.license_no,
				manual_no = this.manual_no,
				net_wt = this.net_wt,
				note_s = this.note_s,
				other_curr = this.other_curr,
				other_mark = this.other_mark,
				other_rate = this.other_rate,
				owner_code = this.owner_code,
				owner_name = this.owner_name,
				pack_no = this.pack_no,
				pay_mode = this.pay_mode,
				pay_way = this.pay_way,
				sfdj0 = this.sfdj0,
				sfdj1 = this.sfdj1,
				sfdj2 = this.sfdj2,
				sfdj3 = this.sfdj3,
				sfdj4 = this.sfdj4,
				sfdj5 = this.sfdj5,
				sfdj6 = this.sfdj6,
				status = this.status,
				tax_rate = this.tax_rate,
				traf_mode = this.traf_mode,
				traf_name = this.traf_name,
				trade_code = this.trade_code,
				trade_coun = this.trade_coun,
				trade_mode = this.trade_mode,
				trade_name = this.trade_name,
				trans_mode = this.trans_mode,
				typer = this.typer,
				use_to_cod = this.use_to_cod,
				wrap_type = this.wrap_type,
				printed = this.printed,
				oper_type = this.oper_type,
				note_1 = this.note_1,
				input_corp = this.input_corp,
				Declar_No = this.Declar_No,
				BP_No = this.BP_No,
				CustomsDocuType = this.CustomsDocuType,
				clpno = this.clpno,
				Sended = this.Sended,
				Confirmdate = this.Confirmdate,
				TransType = this.TransType,
				Trans_Number = this.Trans_Number,
				Cont_Number = this.Cont_Number,
				StdardContNumber = this.StdardContNumber,
				Cont_Size = this.Cont_Size,
				ReturnTax = this.ReturnTax,
				Seal_No = this.Seal_No,
				Cert_No = this.Cert_No,
				VehicleID = this.VehicleID,
				Vehicle_Number = this.Vehicle_Number,
				Remark = this.Remark,
				Customs_Weight = this.Customs_Weight,
			};
		}
	}
}
