//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_forwarder_code
    {
        public int Id { get; set; }
        public string forwarder_code1 { get; set; }
        public string forwarder_name { get; set; }
        public Nullable<bool> StopUse { get; set; }
        public string remark { get; set; }
    }
}
