//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_TruckUnLoadTime
    {
        public int ID { get; set; }
        public string Supplierno { get; set; }
        public string TruckNo { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> GateIn { get; set; }
        public Nullable<System.DateTime> DocRegister { get; set; }
        public Nullable<System.DateTime> CustomsInspection { get; set; }
        public Nullable<System.DateTime> UnLoadStart { get; set; }
        public Nullable<System.DateTime> UnloadFinish { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string Remark { get; set; }
    }
}
