//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Sys_Role
    {
        public int rId { get; set; }
        public int rDepId { get; set; }
        public string rName { get; set; }
        public string rRemark { get; set; }
        public bool rIsShow { get; set; }
        public bool rIsDel { get; set; }
        public System.DateTime rAddTime { get; set; }
    }
}
