//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Truck_CBM_Weight
    {
        public string Truck_Type { get; set; }
        public string InType { get; set; }
        public Nullable<decimal> MIN_CBM { get; set; }
        public Nullable<decimal> MAX_CBM { get; set; }
        public Nullable<decimal> MIN_Weight { get; set; }
        public Nullable<decimal> MAX_Weight { get; set; }
    }
}
