//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_bookingVendor
    {
        public string vendor_code { get; set; }
        public string vendor_name { get; set; }
        public string vendor_contact { get; set; }
        public string vendor_address { get; set; }
        public string vendor_email { get; set; }
        public string vendor_fax { get; set; }
        public string wh_id { get; set; }
        public string forward_code { get; set; }
        public string telNo { get; set; }
        public string consignee { get; set; }
        public string notifyconsignee { get; set; }
        public string secondnotifyconsignee { get; set; }
        public string consigneetel { get; set; }
        public string notifyconsigneetel { get; set; }
        public string secondnotifyconsigneetel { get; set; }
    }
}
