//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Truck_PackingList
    {
        public int plid { get; set; }
        public string vendor_code { get; set; }
        public string so_no { get; set; }
        public string material_groupNo { get; set; }
        public string item { get; set; }
        public string sales_planningNo { get; set; }
        public string descript { get; set; }
        public string hfe { get; set; }
        public string line { get; set; }
        public string fcl { get; set; }
        public string erp { get; set; }
        public string cpo { get; set; }
        public Nullable<int> pcs { get; set; }
        public Nullable<int> ctns { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> total_cbm { get; set; }
        public decimal total_grossweight { get; set; }
        public string dn { get; set; }
        public Nullable<decimal> pn { get; set; }
        public string unit { get; set; }
        public string shipmode { get; set; }
        public string factory { get; set; }
        public Nullable<System.DateTime> vendor_submit_time { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public string delivery_address { get; set; }
        public string account { get; set; }
        public string truck_company { get; set; }
        public string status { get; set; }
        public string delivery_type { get; set; }
        public string invoiceNo { get; set; }
        public string vehicletype { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_person { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> so_submit_date { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public Nullable<System.DateTime> assign_tkcompany_time { get; set; }
        public Nullable<System.DateTime> Reject_Time { get; set; }
        public string Reject_Remark { get; set; }
        public string packlist_remark { get; set; }
        public string cancel_reason { get; set; }
        public string pick_address { get; set; }
        public Nullable<int> so_status { get; set; }
        public string PL_file { get; set; }
    }
}
