//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_DailyTurnover
    {
        public int cbmid { get; set; }
        public string Account { get; set; }
        public int CFS_Year { get; set; }
        public int CFS_Month { get; set; }
        public int CFS_Date { get; set; }
        public Nullable<decimal> Receiving { get; set; }
        public Nullable<decimal> Loading { get; set; }
        public Nullable<decimal> Repacked { get; set; }
        public Nullable<decimal> Repacking { get; set; }
        public string IEFlag { get; set; }
        public Nullable<decimal> ieChange { get; set; }
        public bool confirmed { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
    }
}
