//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_SMFOBDebitNoteRateAutomaticgrowth
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> mouth { get; set; }
        public string so { get; set; }
        public Nullable<System.DateTime> rdate { get; set; }
        public string remark { get; set; }
        public Nullable<int> maxid { get; set; }
    }
}
