//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Truck_Client
    {
        public string Client_Code { get; set; }
        public string Client_Name { get; set; }
        public string Address { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_TelNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string Company { get; set; }
    }
}
