//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_DailyCustomsDocu
    {
        public string ReportDate { get; set; }
        public string CustomsDocNo { get; set; }
        public string CustomsType { get; set; }
        public Nullable<short> ContCount { get; set; }
        public Nullable<short> VehicleCount { get; set; }
        public Nullable<short> STContCount { get; set; }
        public string Port { get; set; }
        public Nullable<decimal> TotalValues { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public string in_no { get; set; }
        public string Container { get; set; }
        public string ClpNo { get; set; }
        public string Remark { get; set; }
        public string Operator { get; set; }
    }
}
