//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_FinalPo_Cancel_Record
    {
        public int cID { get; set; }
        public Nullable<int> pID { get; set; }
        public Nullable<System.DateTime> cancel_time { get; set; }
        public string cancel_user { get; set; }
        public Nullable<int> release { get; set; }
        public string release_user { get; set; }
        public string remark { get; set; }
    }
}
