//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_repertory
    {
        public int rep_id { get; set; }
        public string rep_name { get; set; }
        public string rep_address { get; set; }
        public string rep_phone { get; set; }
        public string rep_connecter { get; set; }
        public string rep_type { get; set; }
        public Nullable<int> rep_state { get; set; }
        public string rep_area { get; set; }
        public string whs_name { get; set; }
    }
}
