//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class recdtl
	{
		public recdtl ToPOCO(bool isPOCO = true){
			return new recdtl(){
				so_no = this.so_no,
				recline = this.recline,
				seq_no = this.seq_no,
				rec_date = this.rec_date,
				prod_des = this.prod_des,
				sku = this.sku,
				po = this.po,
				poctns = this.poctns,
				skn = this.skn,
				c_ono = this.c_ono,
				artno = this.artno,
				size = this.size,
				ctns = this.ctns,
				Qty = this.Qty,
				spec = this.spec,
				pallet = this.pallet,
				pkg = this.pkg,
				unitwei = this.unitwei,
				rweight = this.rweight,
				length = this.length,
				width = this.width,
				height = this.height,
				cbm = this.cbm,
				cl_cbm = this.cl_cbm,
				location = this.location,
				pod = this.pod,
				dest = this.dest,
				Recbal = this.Recbal,
				QtyBal = this.QtyBal,
				remark = this.remark,
				line_no = this.line_no,
			};
		}
	}
}
