//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class rechead
	{
		public rechead ToPOCO(bool isPOCO = true){
			return new rechead(){
				so_no = this.so_no,
				seq_no = this.seq_no,
				client = this.client,
				vendor = this.vendor,
				totctns = this.totctns,
				account = this.account,
				vess_voy = this.vess_voy,
				totcbm = this.totcbm,
				Rec_Status = this.Rec_Status,
				linked = this.linked,
				fsd = this.fsd,
				lsd = this.lsd,
				EDI_Status = this.EDI_Status,
				totwei = this.totwei,
				Ispartial = this.Ispartial,
				SkMark = this.SkMark,
			};
		}
	}
}
