//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class repertory
	{
		public repertory ToPOCO(bool isPOCO = true){
			return new repertory(){
				rep_id = this.rep_id,
				rep_name = this.rep_name,
				rep_address = this.rep_address,
				rep_phone = this.rep_phone,
				rep_connecter = this.rep_connecter,
				rep_type = this.rep_type,
				rep_state = this.rep_state,
				rep_area = this.rep_area,
				whs_name = this.whs_name,
			};
		}
	}
}
