//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class ShipperNameList
	{
		public ShipperNameList ToPOCO(bool isPOCO = true){
			return new ShipperNameList(){
				id = this.id,
				VendorName = this.VendorName,
				MfrName1 = this.MfrName1,
				ShipperName = this.ShipperName,
				Debit_note_Invoice = this.Debit_note_Invoice,
			};
		}
	}
}
