//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class special_item
	{
		public special_item ToPOCO(bool isPOCO = true){
			return new special_item(){
				spid = this.spid,
				seq = this.seq,
				opid = this.opid,
				con_no = this.con_no,
				cont_size = this.cont_size,
				qty = this.qty,
				weight = this.weight,
				cbm = this.cbm,
				unit_price = this.unit_price,
				price = this.price,
				remark1 = this.remark1,
				op = this.op,
				unit = this.unit,
				sfmin = this.sfmin,
				bz = this.bz,
				remark = this.remark,
			};
		}
	}
}
