//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Sys_Permission
	{
		public Sys_Permission ToPOCO(bool isPOCO = true){
			return new Sys_Permission(){
				pid = this.pid,
				pParent = this.pParent,
				pName = this.pName,
				pAreaName = this.pAreaName,
				pControllerName = this.pControllerName,
				pActionName = this.pActionName,
				pFormMethod = this.pFormMethod,
				pOperationType = this.pOperationType,
				pIco = this.pIco,
				pOrder = this.pOrder,
				pIsLink = this.pIsLink,
				pLinkUrl = this.pLinkUrl,
				pIsShow = this.pIsShow,
				pRemark = this.pRemark,
				pIsDel = this.pIsDel,
				pOperTime = this.pOperTime,
			};
		}
	}
}
