//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Sys_Department
	{
		public Sys_Department ToPOCO(bool isPOCO = true){
			return new Sys_Department(){
				depId = this.depId,
				depPid = this.depPid,
				depName = this.depName,
				depRemark = this.depRemark,
				depIconCls = this.depIconCls,
				depIsDel = this.depIsDel,
				depOrder = this.depOrder,
				depAddTime = this.depAddTime,
			};
		}
	}
}
