//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Sys_Log
	{
		public Sys_Log ToPOCO(bool isPOCO = true){
			return new Sys_Log(){
				id = this.id,
				Date = this.Date,
				Thread = this.Thread,
				Level = this.Level,
				Logger = this.Logger,
				Message = this.Message,
				Exception = this.Exception,
			};
		}
	}
}
