//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_CBM_Weight
	{
		public Truck_CBM_Weight ToPOCO(bool isPOCO = true){
			return new Truck_CBM_Weight(){
				Truck_Type = this.Truck_Type,
				InType = this.InType,
				MIN_CBM = this.MIN_CBM,
				MAX_CBM = this.MAX_CBM,
				MIN_Weight = this.MIN_Weight,
				MAX_Weight = this.MAX_Weight,
			};
		}
	}
}
