//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_Client
	{
		public Truck_Client ToPOCO(bool isPOCO = true){
			return new Truck_Client(){
				Client_Code = this.Client_Code,
				Client_Name = this.Client_Name,
				Address = this.Address,
				Contact_Person = this.Contact_Person,
				Contact_TelNo = this.Contact_TelNo,
				Fax = this.Fax,
				Email = this.Email,
				Status = this.Status,
				Company = this.Company,
			};
		}
	}
}
