//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_Invoice_Info_Add
	{
		public Truck_Invoice_Info_Add ToPOCO(bool isPOCO = true){
			return new Truck_Invoice_Info_Add(){
				invoice_no = this.invoice_no,
				invoice_amount = this.invoice_amount,
				receive_forward_invoice = this.receive_forward_invoice,
				settle_payment = this.settle_payment,
				sending_out_FCR = this.sending_out_FCR,
			};
		}
	}
}
