//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_Vendor
	{
		public Truck_Vendor ToPOCO(bool isPOCO = true){
			return new Truck_Vendor(){
				Vendor_Code = this.Vendor_Code,
				Client = this.Client,
				Vendor_Name = this.Vendor_Name,
				Vendor_Name2 = this.Vendor_Name2,
				Simple_Vendor_Name = this.Simple_Vendor_Name,
				Address = this.Address,
				Simple_Address = this.Simple_Address,
				Contact_Person = this.Contact_Person,
				Contact_TelNo = this.Contact_TelNo,
				Fax = this.Fax,
				Email = this.Email,
				Contact_Person2 = this.Contact_Person2,
				Contact_TelNo2 = this.Contact_TelNo2,
				Email2 = this.Email2,
				Contact_Person3 = this.Contact_Person3,
				Contact_TelNo3 = this.Contact_TelNo3,
				Email3 = this.Email3,
				Status = this.Status,
			};
		}
	}
}
