//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cus_hchg
    {
        public string client { get; set; }
        public decimal start_wgt { get; set; }
        public decimal end_wgt { get; set; }
        public decimal chrg_amt { get; set; }
    }
}
