//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_Booking_ClientCharge
	{
		public Truck_Booking_ClientCharge ToPOCO(bool isPOCO = true){
			return new Truck_Booking_ClientCharge(){
				cID = this.cID,
				Booking_Number = this.Booking_Number,
				Seq = this.Seq,
				ChargeName = this.ChargeName,
				Charge = this.Charge,
				Remark = this.Remark,
				Currency = this.Currency,
			};
		}
	}
}
