//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class DailyTurnover
	{
		public DailyTurnover ToPOCO(bool isPOCO = true){
			return new DailyTurnover(){
				cbmid = this.cbmid,
				Account = this.Account,
				CFS_Year = this.CFS_Year,
				CFS_Month = this.CFS_Month,
				CFS_Date = this.CFS_Date,
				Receiving = this.Receiving,
				Loading = this.Loading,
				Repacked = this.Repacked,
				Repacking = this.Repacking,
				IEFlag = this.IEFlag,
				ieChange = this.ieChange,
				confirmed = this.confirmed,
				OperateDate = this.OperateDate,
			};
		}
	}
}
