//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load_Fee
    {
        public int id { get; set; }
        public string clpno { get; set; }
        public string Account { get; set; }
        public string la_no { get; set; }
        public string invoiceno { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> plandate { get; set; }
        public Nullable<decimal> cfschg { get; set; }
    }
}
