//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Sys_Department
    {
        public int depId { get; set; }
        public int depPid { get; set; }
        public string depName { get; set; }
        public string depRemark { get; set; }
        public string depIconCls { get; set; }
        public bool depIsDel { get; set; }
        public Nullable<int> depOrder { get; set; }
        public System.DateTime depAddTime { get; set; }
    }
}
