//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetailEdi
    {
        public string so_no { get; set; }
        public int line_no { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PKG { get; set; }
        public Nullable<decimal> PCS { get; set; }
        public string carrier { get; set; }
        public string description { get; set; }
        public string Remark { get; set; }
        public string PO { get; set; }
        public string commodity { get; set; }
        public string SKU { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public string description3 { get; set; }
        public string description4 { get; set; }
        public Nullable<decimal> rec_weight { get; set; }
        public Nullable<decimal> rec_cbm { get; set; }
        public Nullable<decimal> rec_qty { get; set; }
        public Nullable<decimal> rec_pcs { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public string Product_Description { get; set; }
        public Nullable<System.DateTime> recdate { get; set; }
    }
}
