//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyDataforCustoms
    {
        public string reportdate { get; set; }
        public Nullable<short> jjytgjzxbs { get; set; }
        public Nullable<short> jjytgjzxzs { get; set; }
        public Nullable<decimal> jjytgjzxmz { get; set; }
        public Nullable<decimal> jjytgjzxjz { get; set; }
        public Nullable<short> jjytgdcsl { get; set; }
        public Nullable<decimal> jjytgdcmz { get; set; }
        public Nullable<decimal> jjytgdcjz { get; set; }
        public Nullable<decimal> jjytgmz { get; set; }
        public Nullable<decimal> jjytgjz { get; set; }
        public Nullable<short> jjytgps { get; set; }
        public Nullable<short> jjytgbgd { get; set; }
        public Nullable<short> jjhyzgjzxbs { get; set; }
        public Nullable<short> jjhyzgjzxzs { get; set; }
        public Nullable<decimal> jjhyzgjzxmz { get; set; }
        public Nullable<decimal> jjhyzgjzxjz { get; set; }
        public Nullable<short> jjhyzgdcsl { get; set; }
        public Nullable<decimal> jjhyzgdcmz { get; set; }
        public Nullable<decimal> jjhyzgdcjz { get; set; }
        public Nullable<decimal> jjhyzgmz { get; set; }
        public Nullable<decimal> jjhyzgjz { get; set; }
        public Nullable<short> jjhyzgps { get; set; }
        public Nullable<short> jjhyzgbgd { get; set; }
        public Nullable<short> jjllzgjzxbs { get; set; }
        public Nullable<short> jjllzgjzxzs { get; set; }
        public Nullable<decimal> jjllzgjzxmz { get; set; }
        public Nullable<decimal> jjllzgjzxjz { get; set; }
        public Nullable<short> jjllzgdcsl { get; set; }
        public Nullable<decimal> jjllzgdcmz { get; set; }
        public Nullable<decimal> jjllzgdcjz { get; set; }
        public Nullable<decimal> jjllzgmz { get; set; }
        public Nullable<decimal> jjllzgjz { get; set; }
        public Nullable<short> jjllzgps { get; set; }
        public Nullable<short> jjllzgbgd { get; set; }
        public Nullable<short> cjhyjzxbs { get; set; }
        public Nullable<short> cjhyjzxzs { get; set; }
        public Nullable<decimal> cjhyjzxmz { get; set; }
        public Nullable<decimal> cjhyjzxjz { get; set; }
        public Nullable<short> cjhydcsl { get; set; }
        public Nullable<decimal> cjhydcmz { get; set; }
        public Nullable<decimal> cjhydcjz { get; set; }
        public Nullable<decimal> cjhymz { get; set; }
        public Nullable<decimal> cjhyjz { get; set; }
        public Nullable<short> cjhyps { get; set; }
        public Nullable<short> cjhybgd { get; set; }
        public Nullable<short> cjlljzxbs { get; set; }
        public Nullable<short> cjlljzxzs { get; set; }
        public Nullable<decimal> cjlljzxmz { get; set; }
        public Nullable<decimal> cjlljzxjz { get; set; }
        public Nullable<short> cjlldcsl { get; set; }
        public Nullable<decimal> cjlldcmz { get; set; }
        public Nullable<decimal> cjlldcjz { get; set; }
        public Nullable<decimal> cjllmz { get; set; }
        public Nullable<decimal> cjlljz { get; set; }
        public Nullable<short> cjllps { get; set; }
        public Nullable<short> cjllbgd { get; set; }
        public Nullable<short> cjllzgjzxbs { get; set; }
        public Nullable<short> cjllzgjzxzs { get; set; }
        public Nullable<decimal> cjllzgjzxmz { get; set; }
        public Nullable<decimal> cjllzgjzxjz { get; set; }
        public Nullable<short> cjllzgdcsl { get; set; }
        public Nullable<decimal> cjllzgdcmz { get; set; }
        public Nullable<decimal> cjllzgdcjz { get; set; }
        public Nullable<decimal> cjllzgmz { get; set; }
        public Nullable<decimal> cjllzgjz { get; set; }
        public Nullable<short> cjllzgps { get; set; }
        public Nullable<short> cjllzgbgd { get; set; }
        public Nullable<short> rqqgckybmyjzxbs { get; set; }
        public Nullable<short> rqqgckybmyjzxzs { get; set; }
        public Nullable<decimal> rqqgckybmyjzxmz { get; set; }
        public Nullable<decimal> rqqgckybmyjzxjz { get; set; }
        public Nullable<short> rqqgckybmydcsl { get; set; }
        public Nullable<decimal> rqqgckybmydcmz { get; set; }
        public Nullable<decimal> rqqgckybmydcjz { get; set; }
        public Nullable<decimal> rqqgckybmymz { get; set; }
        public Nullable<decimal> rqqgckybmyjz { get; set; }
        public Nullable<short> rqqgckybmyps { get; set; }
        public Nullable<short> rqqgckybmybgd { get; set; }
        public Nullable<short> rqqgckjgmyjzxbs { get; set; }
        public Nullable<short> rqqgckjgmyjzxzs { get; set; }
        public Nullable<decimal> rqqgckjgmyjzxmz { get; set; }
        public Nullable<decimal> rqqgckjgmyjzxjz { get; set; }
        public Nullable<short> rqqgckjgmydcsl { get; set; }
        public Nullable<decimal> rqqgckjgmydcmz { get; set; }
        public Nullable<decimal> rqqgckjgmydcjz { get; set; }
        public Nullable<decimal> rqqgckjgmymz { get; set; }
        public Nullable<decimal> rqqgckjgmyjz { get; set; }
        public Nullable<short> rqqgckjgmyps { get; set; }
        public Nullable<short> rqqgckjgmybgd { get; set; }
        public Nullable<short> rqzgckjzxbs { get; set; }
        public Nullable<short> rqzgckjzxzs { get; set; }
        public Nullable<decimal> rqzgckjzxmz { get; set; }
        public Nullable<decimal> rqzgckjzxjz { get; set; }
        public Nullable<short> rqzgckdcsl { get; set; }
        public Nullable<decimal> rqzgckdcmz { get; set; }
        public Nullable<decimal> rqzgckdcjz { get; set; }
        public Nullable<decimal> rqzgckmz { get; set; }
        public Nullable<decimal> rqzgckjz { get; set; }
        public Nullable<short> rqzgckps { get; set; }
        public Nullable<short> rqzgckbgd { get; set; }
        public Nullable<short> cqqgjkybmyjzxbs { get; set; }
        public Nullable<short> cqqgjkybmyjzxzs { get; set; }
        public Nullable<decimal> cqqgjkybmyjzxmz { get; set; }
        public Nullable<decimal> cqqgjkybmyjzxjz { get; set; }
        public Nullable<short> cqqgjkybmydcsl { get; set; }
        public Nullable<decimal> cqqgjkybmydcmz { get; set; }
        public Nullable<decimal> cqqgjkybmydcjz { get; set; }
        public Nullable<decimal> cqqgjkybmymz { get; set; }
        public Nullable<decimal> cqqgjkybmyjz { get; set; }
        public Nullable<short> cqqgjkybmyps { get; set; }
        public Nullable<short> cqqgjkybmybgd { get; set; }
        public Nullable<short> cqqgjkjgmyjzxbs { get; set; }
        public Nullable<short> cqqgjkjgmyjzxzs { get; set; }
        public Nullable<decimal> cqqgjkjgmyjzxmz { get; set; }
        public Nullable<decimal> cqqgjkjgmyjzxjz { get; set; }
        public Nullable<short> cqqgjkjgmydcsl { get; set; }
        public Nullable<decimal> cqqgjkjgmydcmz { get; set; }
        public Nullable<decimal> cqqgjkjgmydcjz { get; set; }
        public Nullable<decimal> cqqgjkjgmymz { get; set; }
        public Nullable<decimal> cqqgjkjgmyjz { get; set; }
        public Nullable<short> cqqgjkjgmyps { get; set; }
        public Nullable<short> cqqgjkjgmybgd { get; set; }
        public Nullable<short> cqzgjkjzxbs { get; set; }
        public Nullable<short> cqzgjkjzxzs { get; set; }
        public Nullable<decimal> cqzgjkjzxmz { get; set; }
        public Nullable<decimal> cqzgjkjzxjz { get; set; }
        public Nullable<short> cqzgjkdcsl { get; set; }
        public Nullable<decimal> cqzgjkdcmz { get; set; }
        public Nullable<decimal> cqzgjkdcjz { get; set; }
        public Nullable<decimal> cqzgjkmz { get; set; }
        public Nullable<decimal> cqzgjkjz { get; set; }
        public Nullable<short> cqzgjkps { get; set; }
        public Nullable<short> cqzgjkbgd { get; set; }
        public Nullable<short> jzxbs { get; set; }
        public Nullable<short> jzxzs { get; set; }
        public Nullable<decimal> jzxmz { get; set; }
        public Nullable<decimal> jzxjz { get; set; }
        public Nullable<short> dcsl { get; set; }
        public Nullable<decimal> dcmz { get; set; }
        public Nullable<decimal> dcjz { get; set; }
        public Nullable<decimal> mz { get; set; }
        public Nullable<decimal> jz { get; set; }
        public Nullable<short> ps { get; set; }
        public Nullable<short> bgd { get; set; }
        public Nullable<decimal> kcmz { get; set; }
        public Nullable<decimal> kcjz { get; set; }
        public Nullable<short> jmsps { get; set; }
        public Nullable<short> jmsbgd { get; set; }
        public Nullable<decimal> jmsjz { get; set; }
        public Nullable<short> ysbcktsps { get; set; }
        public Nullable<decimal> ysbcktsmz { get; set; }
        public Nullable<decimal> ysbcktsjz { get; set; }
        public Nullable<decimal> gs { get; set; }
        public Nullable<decimal> sk { get; set; }
        public Nullable<short> zsbgd { get; set; }
        public Nullable<decimal> fckmz { get; set; }
        public Nullable<decimal> fckjz { get; set; }
    }
}
