//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class special_item
    {
        public string spid { get; set; }
        public string seq { get; set; }
        public string opid { get; set; }
        public string con_no { get; set; }
        public string cont_size { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> price { get; set; }
        public string remark1 { get; set; }
        public string op { get; set; }
        public string unit { get; set; }
        public string sfmin { get; set; }
        public string bz { get; set; }
        public string remark { get; set; }
    }
}
