//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_ShipperNameList
    {
        public int id { get; set; }
        public string VendorName { get; set; }
        public string MfrName1 { get; set; }
        public string ShipperName { get; set; }
        public string Debit_note_Invoice { get; set; }
    }
}
