//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class customer
	{
		public customer ToPOCO(bool isPOCO = true){
			return new customer(){
				client = this.client,
				cust_name = this.cust_name,
				address1 = this.address1,
				address2 = this.address2,
				address3 = this.address3,
				tel = this.tel,
				fax = this.fax,
				motion = this.motion,
				email = this.email,
				contact = this.contact,
				sales_name = this.sales_name,
				cbm_price = this.cbm_price,
				free_prd = this.free_prd,
				wght_unit = this.wght_unit,
				stor_fee = this.stor_fee,
				free_day = this.free_day,
				hand_chrge = this.hand_chrge,
				input_date = this.input_date,
				remark = this.remark,
			};
		}
	}
}
