//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class out_head_cy
    {
        public out_head_cy()
        {
            this.out_item_cy = new HashSet<out_item_cy>();
        }
    
        public int ID { get; set; }
        public string la_no { get; set; }
        public string cont_no { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string seal_no { get; set; }
        public string cont_type { get; set; }
        public string POE { get; set; }
        public string booking_number { get; set; }
        public string destination { get; set; }
        public string division { get; set; }
        public Nullable<decimal> total_pcs { get; set; }
        public Nullable<int> total_ctn { get; set; }
        public Nullable<decimal> total_cbm { get; set; }
        public Nullable<decimal> total_weight { get; set; }
        public string acceptance { get; set; }
        public string Carrier { get; set; }
        public string MBL { get; set; }
        public string HBL { get; set; }
        public Nullable<System.DateTime> FcrData { get; set; }
        public string ECV_Status { get; set; }
        public string shipment_id { get; set; }
        public Nullable<System.DateTime> Closingdate { get; set; }
    
        public virtual ICollection<out_item_cy> out_item_cy { get; set; }
    }
}
