//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_PackingList
	{
		public Truck_PackingList ToPOCO(bool isPOCO = true){
			return new Truck_PackingList(){
				plid = this.plid,
				vendor_code = this.vendor_code,
				so_no = this.so_no,
				material_groupNo = this.material_groupNo,
				item = this.item,
				sales_planningNo = this.sales_planningNo,
				descript = this.descript,
				hfe = this.hfe,
				line = this.line,
				fcl = this.fcl,
				erp = this.erp,
				cpo = this.cpo,
				pcs = this.pcs,
				ctns = this.ctns,
				length = this.length,
				width = this.width,
				height = this.height,
				total_cbm = this.total_cbm,
				total_grossweight = this.total_grossweight,
				dn = this.dn,
				pn = this.pn,
				unit = this.unit,
				shipmode = this.shipmode,
				factory = this.factory,
				vendor_submit_time = this.vendor_submit_time,
				pick_date = this.pick_date,
				delivery_address = this.delivery_address,
				account = this.account,
				truck_company = this.truck_company,
				status = this.status,
				delivery_type = this.delivery_type,
				invoiceNo = this.invoiceNo,
				vehicletype = this.vehicletype,
				cancel_date = this.cancel_date,
				cancel_person = this.cancel_person,
				remarks = this.remarks,
				so_submit_date = this.so_submit_date,
				closing_date = this.closing_date,
				assign_tkcompany_time = this.assign_tkcompany_time,
				Reject_Time = this.Reject_Time,
				Reject_Remark = this.Reject_Remark,
				packlist_remark = this.packlist_remark,
				cancel_reason = this.cancel_reason,
				pick_address = this.pick_address,
				so_status = this.so_status,
				PL_file = this.PL_file,
			};
		}
	}
}
