//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_custin
    {
        public string in_no { get; set; }
        public string decl_mode { get; set; }
        public string factory { get; set; }
        public Nullable<System.DateTime> decldate { get; set; }
        public Nullable<System.DateTime> arr_time { get; set; }
        public Nullable<System.DateTime> ingate_time { get; set; }
        public Nullable<System.DateTime> dev_time { get; set; }
        public Nullable<System.DateTime> compl_time { get; set; }
        public string remark { get; set; }
        public Nullable<bool> duty { get; set; }
    }
}
