//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalVendorInputLog
    {
        public int fID { get; set; }
        public string loginName { get; set; }
        public string logInfo { get; set; }
        public Nullable<System.DateTime> logTime { get; set; }
        public string actionType { get; set; }
        public Nullable<int> bID { get; set; }
    }
}
