//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class TruckUnLoadTime
	{
		public TruckUnLoadTime ToPOCO(bool isPOCO = true){
			return new TruckUnLoadTime(){
				ID = this.ID,
				Supplierno = this.Supplierno,
				TruckNo = this.TruckNo,
				Employee = this.Employee,
				GateIn = this.GateIn,
				DocRegister = this.DocRegister,
				CustomsInspection = this.CustomsInspection,
				UnLoadStart = this.UnLoadStart,
				UnloadFinish = this.UnloadFinish,
				Qty = this.Qty,
				CBM = this.CBM,
				Remark = this.Remark,
			};
		}
	}
}
