//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recdtl
    {
        public string so_no { get; set; }
        public string recline { get; set; }
        public decimal seq_no { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string prod_des { get; set; }
        public string sku { get; set; }
        public string po { get; set; }
        public Nullable<int> poctns { get; set; }
        public string skn { get; set; }
        public string c_ono { get; set; }
        public string artno { get; set; }
        public string size { get; set; }
        public Nullable<int> ctns { get; set; }
        public Nullable<int> Qty { get; set; }
        public string spec { get; set; }
        public Nullable<int> pallet { get; set; }
        public string pkg { get; set; }
        public Nullable<decimal> unitwei { get; set; }
        public Nullable<decimal> rweight { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<decimal> cl_cbm { get; set; }
        public string location { get; set; }
        public string pod { get; set; }
        public string dest { get; set; }
        public Nullable<int> Recbal { get; set; }
        public Nullable<int> QtyBal { get; set; }
        public string remark { get; set; }
        public Nullable<int> line_no { get; set; }
    }
}
