//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FCR_Head
	{
		public FCR_Head ToPOCO(bool isPOCO = true){
			return new FCR_Head(){
				id = this.id,
				fcr_no = this.fcr_no,
				factory = this.factory,
				bl_no = this.bl_no,
				vessel = this.vessel,
				voyage = this.voyage,
				discharging_port = this.discharging_port,
				destination = this.destination,
				docReceived_date = this.docReceived_date,
				cargoReceived_date = this.cargoReceived_date,
				reg_date = this.reg_date,
				last_modify_date = this.last_modify_date,
				creater_user = this.creater_user,
				last_modify_user = this.last_modify_user,
			};
		}
	}
}
