//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalVendorInput
    {
        public FinalVendorInput()
        {
            this.FinalVendorInputTrucking = new HashSet<FinalVendorInputTrucking>();
        }
    
        public int VID { get; set; }
        public int PID { get; set; }
        public string PO_Line { get; set; }
        public string Created_By { get; set; }
        public string Matl_Group_Sales { get; set; }
        public string Matrix { get; set; }
        public string Slip_Sheet { get; set; }
        public string Packing_Status { get; set; }
        public Nullable<System.DateTime> Inspection_End_Date { get; set; }
        public string Inspection_Result { get; set; }
        public string FOB_Local_Charges_Settlement { get; set; }
        public Nullable<System.DateTime> FCR_Bill_Return_Date { get; set; }
        public Nullable<System.DateTime> Certificate_Application_Date { get; set; }
        public Nullable<System.DateTime> Certificate_Return_TO_SMDate { get; set; }
        public Nullable<int> Qty_Delivered { get; set; }
        public string To_be_del { get; set; }
        public string OTD_Reason_Code { get; set; }
        public string Delay_Details { get; set; }
        public Nullable<int> Carton_delivered { get; set; }
        public string Booking_No { get; set; }
        public Nullable<System.DateTime> Loading_Date { get; set; }
        public Nullable<System.DateTime> CFS_Closing_Date { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Shipment_Status { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string loginName { get; set; }
        public string Dischaging_Port { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Loading_Port { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> CY_Closing_Date { get; set; }
        public Nullable<System.DateTime> SI_Cut_Time { get; set; }
        public Nullable<System.DateTime> Arrive_WHS_Date { get; set; }
        public Nullable<System.DateTime> Arrive_terminal_Date { get; set; }
        public Nullable<decimal> Delivery_CBM { get; set; }
        public string Container_NO { get; set; }
        public string Seal_NO { get; set; }
        public string Vehicle_Type { get; set; }
        public Nullable<System.DateTime> SO_Release_Date { get; set; }
        public Nullable<System.DateTime> CY_Open_date { get; set; }
        public Nullable<System.DateTime> CFS_Open_Date { get; set; }
        public string Ship_Mode { get; set; }
        public string Forward_Name { get; set; }
        public string Courier_tracking_no { get; set; }
        public Nullable<System.DateTime> Update_GR_time { get; set; }
    
        public virtual FinalPoList FinalPoList { get; set; }
        public virtual ICollection<FinalVendorInputTrucking> FinalVendorInputTrucking { get; set; }
    }
}
