//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_PO
	{
		public Truck_PO ToPOCO(bool isPOCO = true){
			return new Truck_PO(){
				ID = this.ID,
				VendorCode = this.VendorCode,
				VendorName = this.VendorName,
				Customer_Name = this.Customer_Name,
				Customer_PO = this.Customer_PO,
				Line = this.Line,
				Item = this.Item,
				Material = this.Material,
				STO = this.STO,
				Length = this.Length,
				Width = this.Width,
				Height = this.Height,
				Deliv_Date = this.Deliv_Date,
				Pcs = this.Pcs,
				Ctn = this.Ctn,
				GrossWeight = this.GrossWeight,
				CBM = this.CBM,
				First_Date = this.First_Date,
				Cancel_Date = this.Cancel_Date,
			};
		}
	}
}
