//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_out_head
    {
        public string clpno { get; set; }
        public string la_no { get; set; }
        public string client { get; set; }
        public string cont_no { get; set; }
        public string seal_no { get; set; }
        public string pod { get; set; }
        public string division { get; set; }
        public string destination { get; set; }
        public string cust_ordno { get; set; }
        public string booking { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string cont_size { get; set; }
        public Nullable<System.DateTime> Plan_date { get; set; }
        public Nullable<System.DateTime> loa_date { get; set; }
        public Nullable<System.DateTime> deliv_date { get; set; }
        public Nullable<System.DateTime> sail_date { get; set; }
        public string carrier { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<System.DateTime> SI_Date { get; set; }
        public string shuttle { get; set; }
        public Nullable<decimal> shuttle_fee { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
        public string decl_mode { get; set; }
        public string loadport { get; set; }
        public string export_form { get; set; }
        public Nullable<decimal> totalqty { get; set; }
        public Nullable<decimal> totalcbm { get; set; }
        public Nullable<System.DateTime> decl_date { get; set; }
        public string ieflag { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> remark1 { get; set; }
        public string remark2 { get; set; }
        public bool beloaded { get; set; }
        public string trans_type { get; set; }
        public Nullable<System.DateTime> recla_date { get; set; }
        public Nullable<System.DateTime> terclos_date { get; set; }
        public Nullable<System.DateTime> permit_date { get; set; }
        public Nullable<System.DateTime> email_date { get; set; }
        public string G_Veh { get; set; }
        public Nullable<System.DateTime> G_Order { get; set; }
        public Nullable<System.DateTime> G_Back { get; set; }
        public string B_Veh { get; set; }
        public Nullable<System.DateTime> B_Order { get; set; }
        public Nullable<System.DateTime> B_Back { get; set; }
        public string ContYard { get; set; }
        public string TerYard { get; set; }
        public Nullable<decimal> ExchFee { get; set; }
        public Nullable<decimal> ContFee { get; set; }
        public Nullable<decimal> CharDocFee { get; set; }
        public Nullable<decimal> SuffocatingFee { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> StuffStart { get; set; }
        public Nullable<System.DateTime> Stufffinish { get; set; }
        public string BLNO { get; set; }
        public string HBL { get; set; }
        public string PickAddress { get; set; }
        public string ReturnAddress { get; set; }
        public Nullable<decimal> VGM_Weight { get; set; }
        public Nullable<int> Customs_Declaration { get; set; }
        public string forwarder_code { get; set; }
        public Nullable<System.DateTime> Terminal_POD_UploadDate { get; set; }
        public string shipment_ID { get; set; }
    }
}
