//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_ypmfuser
    {
        public string user_name { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string passcode { get; set; }
        public Nullable<int> layer { get; set; }
        public Nullable<bool> recloa { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> dec { get; set; }
        public Nullable<bool> acc { get; set; }
        public Nullable<bool> adminname { get; set; }
        public Nullable<bool> guest { get; set; }
        public string email { get; set; }
    }
}
