//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class SpsOperate
	{
		public SpsOperate ToPOCO(bool isPOCO = true){
			return new SpsOperate(){
				ID = this.ID,
				OrderNo = this.OrderNo,
				OperateDate = this.OperateDate,
				StartTime = this.StartTime,
				EndTime = this.EndTime,
				Employer = this.Employer,
				Account = this.Account,
				Ctn = this.Ctn,
				Paires = this.Paires,
				CBM = this.CBM,
				Brand = this.Brand,
				Type = this.Type,
				Warehouse = this.Warehouse,
			};
		}
	}
}
