//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Order
    {
        public int ID { get; set; }
        public string Vendor { get; set; }
        public string Vendor_Name { get; set; }
        public string ClientCode { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_PO { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string SalesOrderSTO { get; set; }
        public string Item_NO { get; set; }
        public string Customer_Material_Number { get; set; }
        public string Sales_Material { get; set; }
        public string Material { get; set; }
        public string Short_text { get; set; }
        public Nullable<System.DateTime> Delev_Date { get; set; }
        public string Item { get; set; }
        public Nullable<int> Po_Quantity { get; set; }
        public Nullable<int> Total_Carton { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<decimal> TotalVolume { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public string ShipTo_City { get; set; }
        public string DestCode { get; set; }
        public string ShipTo_Name { get; set; }
        public string ShipTo_Country { get; set; }
        public string Mfr_Country { get; set; }
        public string Mfr_City { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<int> GroupNumber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Truck_Dest Truck_Dest { get; set; }
    }
}
