//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inhead
    {
        public int ihid { get; set; }
        public string pre_entry { get; set; }
        public string act_date { get; set; }
        public string agent_code { get; set; }
        public string agent_name { get; set; }
        public string appl_no { get; set; }
        public string appr_no { get; set; }
        public string bill_no { get; set; }
        public string carbox_no { get; set; }
        public string cert_mark { get; set; }
        public string co_owner { get; set; }
        public string contr_no { get; set; }
        public string customs_co { get; set; }
        public string cut_mode { get; set; }
        public string d_date { get; set; }
        public string port_line { get; set; }
        public string district_c { get; set; }
        public string entry_id { get; set; }
        public string ex_source { get; set; }
        public string factory { get; set; }
        public string fee_curr { get; set; }
        public string fee_mark { get; set; }
        public Nullable<decimal> fee_rate { get; set; }
        public string givetax { get; set; }
        public decimal gross_wt { get; set; }
        public string i_e_date { get; set; }
        public string i_e_port { get; set; }
        public Nullable<short> duty_ratio { get; set; }
        public string insur_curr { get; set; }
        public string insur_mark { get; set; }
        public Nullable<decimal> insur_rate { get; set; }
        public Nullable<int> items_no { get; set; }
        public string license_no { get; set; }
        public string manual_no { get; set; }
        public decimal net_wt { get; set; }
        public string note_s { get; set; }
        public string other_curr { get; set; }
        public string other_mark { get; set; }
        public Nullable<decimal> other_rate { get; set; }
        public string owner_code { get; set; }
        public string owner_name { get; set; }
        public decimal pack_no { get; set; }
        public string pay_mode { get; set; }
        public string pay_way { get; set; }
        public string sfdj0 { get; set; }
        public string sfdj1 { get; set; }
        public string sfdj2 { get; set; }
        public string sfdj3 { get; set; }
        public string sfdj4 { get; set; }
        public string sfdj5 { get; set; }
        public string sfdj6 { get; set; }
        public string status { get; set; }
        public Nullable<short> tax_rate { get; set; }
        public string traf_mode { get; set; }
        public string traf_name { get; set; }
        public string trade_code { get; set; }
        public string trade_coun { get; set; }
        public string trade_mode { get; set; }
        public string trade_name { get; set; }
        public string trans_mode { get; set; }
        public string typer { get; set; }
        public string use_to_cod { get; set; }
        public string wrap_type { get; set; }
        public string printed { get; set; }
        public string oper_type { get; set; }
        public string note_1 { get; set; }
        public string input_corp { get; set; }
        public string In_No { get; set; }
        public string Declar_No { get; set; }
        public string BP_No { get; set; }
        public string CustomsDocuType { get; set; }
        public bool LinkToSo { get; set; }
        public bool Sended { get; set; }
        public Nullable<System.DateTime> Confirmdate { get; set; }
        public string TransType { get; set; }
        public Nullable<short> Trans_Number { get; set; }
        public Nullable<short> Cont_Number { get; set; }
        public Nullable<short> StdardContNumber { get; set; }
        public string Cont_Size { get; set; }
        public bool ReturnTax { get; set; }
        public string Seal_No { get; set; }
        public string Cert_No { get; set; }
        public string VehicleID { get; set; }
        public Nullable<short> Vehicle_Number { get; set; }
        public string Remark { get; set; }
    }
}
