//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class BookingDetailEdi
	{
		public BookingDetailEdi ToPOCO(bool isPOCO = true){
			return new BookingDetailEdi(){
				so_no = this.so_no,
				line_no = this.line_no,
				weight = this.weight,
				cbm = this.cbm,
				Qty = this.Qty,
				PKG = this.PKG,
				PCS = this.PCS,
				carrier = this.carrier,
				description = this.description,
				Remark = this.Remark,
				PO = this.PO,
				commodity = this.commodity,
				SKU = this.SKU,
				description1 = this.description1,
				description2 = this.description2,
				description3 = this.description3,
				description4 = this.description4,
				rec_weight = this.rec_weight,
				rec_cbm = this.rec_cbm,
				rec_qty = this.rec_qty,
				rec_pcs = this.rec_pcs,
				length = this.length,
				width = this.width,
				height = this.height,
				Product_Description = this.Product_Description,
				recdate = this.recdate,
			};
		}
	}
}
