//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class FinalVendorInput
	{
		public FinalVendorInput ToPOCO(bool isPOCO = true){
			return new FinalVendorInput(){
				VID = this.VID,
				PID = this.PID,
				PO_Line = this.PO_Line,
				Created_By = this.Created_By,
				Matl_Group_Sales = this.Matl_Group_Sales,
				Matrix = this.Matrix,
				Slip_Sheet = this.Slip_Sheet,
				Packing_Status = this.Packing_Status,
				Inspection_End_Date = this.Inspection_End_Date,
				Inspection_Result = this.Inspection_Result,
				FOB_Local_Charges_Settlement = this.FOB_Local_Charges_Settlement,
				FCR_Bill_Return_Date = this.FCR_Bill_Return_Date,
				Certificate_Application_Date = this.Certificate_Application_Date,
				Certificate_Return_TO_SMDate = this.Certificate_Return_TO_SMDate,
				Qty_Delivered = this.Qty_Delivered,
				To_be_del = this.To_be_del,
				OTD_Reason_Code = this.OTD_Reason_Code,
				Delay_Details = this.Delay_Details,
				Carton_delivered = this.Carton_delivered,
				Booking_No = this.Booking_No,
				Loading_Date = this.Loading_Date,
				CFS_Closing_Date = this.CFS_Closing_Date,
				ETD = this.ETD,
				Shipment_Status = this.Shipment_Status,
				InputTime = this.InputTime,
				loginName = this.loginName,
				Dischaging_Port = this.Dischaging_Port,
				Vessel = this.Vessel,
				Voyage = this.Voyage,
				Loading_Port = this.Loading_Port,
				Booking_Date = this.Booking_Date,
				ETA = this.ETA,
				CY_Closing_Date = this.CY_Closing_Date,
				SI_Cut_Time = this.SI_Cut_Time,
				Arrive_WHS_Date = this.Arrive_WHS_Date,
				Arrive_terminal_Date = this.Arrive_terminal_Date,
				Delivery_CBM = this.Delivery_CBM,
				Container_NO = this.Container_NO,
				Seal_NO = this.Seal_NO,
				Vehicle_Type = this.Vehicle_Type,
				SO_Release_Date = this.SO_Release_Date,
				CY_Open_date = this.CY_Open_date,
				CFS_Open_Date = this.CFS_Open_Date,
				Ship_Mode = this.Ship_Mode,
				Forward_Name = this.Forward_Name,
				Courier_tracking_no = this.Courier_tracking_no,
				Update_GR_time = this.Update_GR_time,
			};
		}
	}
}
