//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class special
	{
		public special ToPOCO(bool isPOCO = true){
			return new special(){
				spid = this.spid,
				client = this.client,
				cust_name = this.cust_name,
				consg_code = this.consg_code,
				consg_name = this.consg_name,
				opdate = this.opdate,
				factory = this.factory,
				remark = this.remark,
				remark2 = this.remark2,
				contact = this.contact,
				confirmdate = this.confirmdate,
			};
		}
	}
}
