//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_RecRegistrationItems
    {
        public int RegDID { get; set; }
        public string In_No { get; set; }
        public short ItemSeq { get; set; }
        public string So_No { get; set; }
        public int Amount { get; set; }
        public string Client { get; set; }
        public string Prod_Des { get; set; }
        public Nullable<bool> Inspection { get; set; }
        public string Remark { get; set; }
    }
}
