//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_item
    {
        public string so_no { get; set; }
        public string seq { get; set; }
        public string item_no { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public Nullable<System.DateTime> decldate { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
        public string dest_port { get; set; }
        public string destination { get; set; }
        public string stk { get; set; }
        public string po { get; set; }
        public string sku { get; set; }
        public string case_no { get; set; }
        public string style_no { get; set; }
        public string location { get; set; }
        public string in_no { get; set; }
        public string desc_code { get; set; }
        public Nullable<int> pallet { get; set; }
        public Nullable<int> pltbal { get; set; }
        public Nullable<int> ctn { get; set; }
        public Nullable<int> ctnbal { get; set; }
        public Nullable<decimal> pcs { get; set; }
        public Nullable<decimal> pcsbal { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> qtybal { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> poqty { get; set; }
        public Nullable<decimal> spec { get; set; }
        public string size { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public string cubeunit { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> unitwei { get; set; }
        public string kgs_unit { get; set; }
        public Nullable<decimal> netwei { get; set; }
        public Nullable<decimal> unitnetwei { get; set; }
        public Nullable<decimal> netwei_unit { get; set; }
        public string shuttle { get; set; }
        public Nullable<decimal> shuttle_fee { get; set; }
        public string patterno { get; set; }
        public string pattern_name { get; set; }
        public string currency { get; set; }
        public bool refund { get; set; }
        public string part { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string seal_no { get; set; }
        public Nullable<System.DateTime> etd { get; set; }
        public Nullable<System.DateTime> eta { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> remark1 { get; set; }
        public string remark2 { get; set; }
        public string commodity { get; set; }
        public bool repacked { get; set; }
        public string Prod_des { get; set; }
        public Nullable<decimal> pcsperqty { get; set; }
        public string line { get; set; }
        public string description { get; set; }
        public Nullable<decimal> SI_Weight { get; set; }
        public string SI_WeightRemark { get; set; }
    }
}
