//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Truck_Invoice_Info
    {
        public string invoice_no { get; set; }
        public string so { get; set; }
        public string sales_order { get; set; }
        public string line { get; set; }
        public string ship_mode { get; set; }
        public bool BL { get; set; }
    }
}
