//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class category
	{
		public category ToPOCO(bool isPOCO = true){
			return new category(){
				id = this.id,
				client = this.client,
				consg_code = this.consg_code,
				desc_code = this.desc_code,
				desc_dec = this.desc_dec,
			};
		}
	}
}
