//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class OutList
	{
		public OutList ToPOCO(bool isPOCO = true){
			return new OutList(){
				ebgID = this.ebgID,
				pre_entry = this.pre_entry,
				g_no = this.g_no,
				code_s = this.code_s,
				code_t = this.code_t,
				class_mark = this.class_mark,
				contr_item = this.contr_item,
				curr_code = this.curr_code,
				duty_mode = this.duty_mode,
				factor = this.factor,
				g_name = this.g_name,
				g_qty = this.g_qty,
				g_spec = this.g_spec,
				g_unit = this.g_unit,
				goods_id = this.goods_id,
				qty_1 = this.qty_1,
				qty_2 = this.qty_2,
				orign_coun = this.orign_coun,
				trade_ttl = this.trade_ttl,
				unit_code1 = this.unit_code1,
				unit_code2 = this.unit_code2,
				unit_price = this.unit_price,
				g_weight = this.g_weight,
				g_netwei = this.g_netwei,
				exg_ver = this.exg_ver,
				w_code_t = this.w_code_t,
				w_code_s = this.w_code_s,
				w_curr = this.w_curr,
				w_total = this.w_total,
				pack_no = this.pack_no,
				CustomsDocuType = this.CustomsDocuType,
				ClpNo = this.ClpNo,
			};
		}
	}
}
