//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bn_Zodiac
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public string YunShi { get; set; }
        public string XingGe { get; set; }
        public string AiQing { get; set; }
        public string HunPei { get; set; }
        public string NianLing { get; set; }
        public string WenZhang { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> OperDate { get; set; }
    }
}
