//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class bookingHead
	{
		public bookingHead ToPOCO(bool isPOCO = true){
			return new bookingHead(){
				hId = this.hId,
				so_no = this.so_no,
				Shipper = this.Shipper,
				Consignee = this.Consignee,
				Notifyparty = this.Notifyparty,
				AlsoNotify = this.AlsoNotify,
				ContSize = this.ContSize,
				UnloadingPort = this.UnloadingPort,
				LoadingPort = this.LoadingPort,
				DestinationPort = this.DestinationPort,
				OpenDate = this.OpenDate,
				CloseDate = this.CloseDate,
				InputDate = this.InputDate,
				//operator = this.operator,
				TelNo = this.TelNo,
				TotGrossWeight = this.TotGrossWeight,
				TotPcs = this.TotPcs,
				TotCtn = this.TotCtn,
				TotCBM = this.TotCBM,
				Remark = this.Remark,
				CancelDate = this.CancelDate,
				precastInHouseDate = this.precastInHouseDate,
				account = this.account,
				inputOperator = this.inputOperator,
				cancelOperator = this.cancelOperator,
				vessel = this.vessel,
				voyage = this.voyage,
				BLNO = this.BLNO,
				ETD = this.ETD,
				SI_cut_off = this.SI_cut_off,
				CY_closing_date = this.CY_closing_date,
				Client_Operator = this.Client_Operator,
				cutomer_name = this.cutomer_name,
				first_date = this.first_date,
				cancel_date = this.cancel_date,
				confirm_date = this.confirm_date,
				clpno = this.clpno,
				client = this.client,
				service_type = this.service_type,
				printed = this.printed,
				shipping_mark = this.shipping_mark,
				Shipper2 = this.Shipper2,
				Consignee2 = this.Consignee2,
				Notifyparty2 = this.Notifyparty2,
			};
		}
	}
}
