//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_FinalLoadingPlan_Payment
    {
        public int ID { get; set; }
        public string JOB_NO { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<decimal> Label_Fee { get; set; }
        public string Fwd_INV { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Oth_Charge { get; set; }
        public string InvoiceNo { get; set; }
    }
}
