//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadPlanUpdateRecord
    {
        public int uID { get; set; }
        public Nullable<int> lID { get; set; }
        public string update_content { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
    
        public virtual FinalLoadingPlan FinalLoadingPlan { get; set; }
    }
}
