//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_invoice
    {
        public int iID { get; set; }
        public string invoiceNo { get; set; }
        public string so_no { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<decimal> Total_USD { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string vendor { get; set; }
        public Nullable<decimal> cbm_price { get; set; }
        public Nullable<decimal> cbm { get; set; }
    }
}
