//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class out_head
	{
		public out_head ToPOCO(bool isPOCO = true){
			return new out_head(){
				clpno = this.clpno,
				la_no = this.la_no,
				client = this.client,
				cont_no = this.cont_no,
				seal_no = this.seal_no,
				pod = this.pod,
				division = this.division,
				destination = this.destination,
				cust_ordno = this.cust_ordno,
				booking = this.booking,
				vessel = this.vessel,
				voyage = this.voyage,
				cont_size = this.cont_size,
				Plan_date = this.Plan_date,
				loa_date = this.loa_date,
				deliv_date = this.deliv_date,
				sail_date = this.sail_date,
				carrier = this.carrier,
				close_date = this.close_date,
				SI_Date = this.SI_Date,
				shuttle = this.shuttle,
				shuttle_fee = this.shuttle_fee,
				input_date = this.input_date,
				decl_mode = this.decl_mode,
				loadport = this.loadport,
				export_form = this.export_form,
				totalqty = this.totalqty,
				totalcbm = this.totalcbm,
				decl_date = this.decl_date,
				ieflag = this.ieflag,
				remark = this.remark,
				remark1 = this.remark1,
				remark2 = this.remark2,
				beloaded = this.beloaded,
				trans_type = this.trans_type,
				recla_date = this.recla_date,
				terclos_date = this.terclos_date,
				permit_date = this.permit_date,
				email_date = this.email_date,
				G_Veh = this.G_Veh,
				G_Order = this.G_Order,
				G_Back = this.G_Back,
				B_Veh = this.B_Veh,
				B_Order = this.B_Order,
				B_Back = this.B_Back,
				ContYard = this.ContYard,
				TerYard = this.TerYard,
				ExchFee = this.ExchFee,
				ContFee = this.ContFee,
				CharDocFee = this.CharDocFee,
				SuffocatingFee = this.SuffocatingFee,
				Employee = this.Employee,
				StuffStart = this.StuffStart,
				Stufffinish = this.Stufffinish,
				BLNO = this.BLNO,
				HBL = this.HBL,
				PickAddress = this.PickAddress,
				ReturnAddress = this.ReturnAddress,
				VGM_Weight = this.VGM_Weight,
				Customs_Declaration = this.Customs_Declaration,
				forwarder_code = this.forwarder_code,
				Terminal_POD_UploadDate = this.Terminal_POD_UploadDate,
				shipment_ID = this.shipment_ID,
			};
		}
	}
}
