//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class Truck_Booking_Head
	{
		public Truck_Booking_Head ToPOCO(bool isPOCO = true){
			return new Truck_Booking_Head(){
				Booking_Number = this.Booking_Number,
				Clpno = this.Clpno,
				Account = this.Account,
				Intype = this.Intype,
				Delivery_Type = this.Delivery_Type,
				Transport_Type = this.Transport_Type,
				Declare_Port = this.Declare_Port,
				Storage_Yard = this.Storage_Yard,
				Factory = this.Factory,
				Factory_Contact_Person = this.Factory_Contact_Person,
				Factory_Contact_TelNo = this.Factory_Contact_TelNo,
				Truck_Company = this.Truck_Company,
				Driver_Name = this.Driver_Name,
				Driver_TelNo = this.Driver_TelNo,
				Cont_NO = this.Cont_NO,
				Seal_NO = this.Seal_NO,
				Frame_Type = this.Frame_Type,
				HeadStockWeight = this.HeadStockWeight,
				FrameWeight = this.FrameWeight,
				ContainerWeight = this.ContainerWeight,
				Pick_address = this.Pick_address,
				Return_address = this.Return_address,
				Loading_address = this.Loading_address,
				CBM = this.CBM,
				GrossWeight = this.GrossWeight,
				CTN = this.CTN,
				Vdr_Pickup_date = this.Vdr_Pickup_date,
				Rq_Arrive_Whs_time = this.Rq_Arrive_Whs_time,
				Rq_Arrive_Dest_time = this.Rq_Arrive_Dest_time,
				Arrive_factory_time = this.Arrive_factory_time,
				Leave_factory_time = this.Leave_factory_time,
				Leave_customs_time = this.Leave_customs_time,
				Arrive_Whs_time = this.Arrive_Whs_time,
				si_date = this.si_date,
				terclos_date = this.terclos_date,
				closdate = this.closdate,
				Vehicletype = this.Vehicletype,
				Fongguan_Address = this.Fongguan_Address,
				Vehicle_number = this.Vehicle_number,
				VendorCode = this.VendorCode,
				VendorName = this.VendorName,
				Carrier = this.Carrier,
				CustomsNo = this.CustomsNo,
				Customs_Password = this.Customs_Password,
				DingCangNO = this.DingCangNO,
				Rocars = this.Rocars,
				HK_Customs_Clearance = this.HK_Customs_Clearance,
				HK_Local_Transport = this.HK_Local_Transport,
				Confirm_date = this.Confirm_date,
				CancelDate = this.CancelDate,
				Cancelperson = this.Cancelperson,
				Own_Company = this.Own_Company,
				Create_Date = this.Create_Date,
				Create_Person = this.Create_Person,
				InvoiceNo = this.InvoiceNo,
				Release_Pass = this.Release_Pass,
				Remark = this.Remark,
				Remark2 = this.Remark2,
				Electronic_Lock = this.Electronic_Lock,
				Fin_Invo = this.Fin_Invo,
				LatestUpdateTime = this.LatestUpdateTime,
				TongGuanCard = this.TongGuanCard,
				Invoice_Date = this.Invoice_Date,
				Backway_Time = this.Backway_Time,
				Terminal_Time = this.Terminal_Time,
				FactorySeal_Time = this.FactorySeal_Time,
				Reject_Time = this.Reject_Time,
				Truck_CancelReason = this.Truck_CancelReason,
				Container_Upload_Time = this.Container_Upload_Time,
				Seal_Upload_Time = this.Seal_Upload_Time,
				Out_Factory_Time = this.Out_Factory_Time,
				Receipt_Upload_time = this.Receipt_Upload_time,
				Start_Unloading_time = this.Start_Unloading_time,
				Leave_Terminal_time = this.Leave_Terminal_time,
			};
		}
	}
}
