//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class DailyCustomsDocu
	{
		public DailyCustomsDocu ToPOCO(bool isPOCO = true){
			return new DailyCustomsDocu(){
				ReportDate = this.ReportDate,
				CustomsDocNo = this.CustomsDocNo,
				CustomsType = this.CustomsType,
				ContCount = this.ContCount,
				VehicleCount = this.VehicleCount,
				STContCount = this.STContCount,
				Port = this.Port,
				TotalValues = this.TotalValues,
				Currency = this.Currency,
				gross_wt = this.gross_wt,
				in_no = this.in_no,
				Container = this.Container,
				ClpNo = this.ClpNo,
				Remark = this.Remark,
				Operator = this.Operator,
			};
		}
	}
}
