//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class newpacklist
	{
		public newpacklist ToPOCO(bool isPOCO = true){
			return new newpacklist(){
				PID = this.PID,
				so_no = this.so_no,
				newseq = this.newseq,
				booking = this.booking,
				item_no = this.item_no,
				seq = this.seq,
				pcs = this.pcs,
			};
		}
	}
}
