//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class vessel
	{
		public vessel ToPOCO(bool isPOCO = true){
			return new vessel(){
				vessel1 = this.vessel1,
				voyage = this.voyage,
				carry_no = this.carry_no,
				agent = this.agent,
				vessel_no = this.vessel_no,
				close_date = this.close_date,
				close_time = this.close_time,
				sail_date = this.sail_date,
				dest_port = this.dest_port,
				ETD = this.ETD,
				ETA = this.ETA,
				load_no = this.load_no,
			};
		}
	}
}
