//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class consignee
	{
		public consignee ToPOCO(bool isPOCO = true){
			return new consignee(){
				client = this.client,
				consg_code = this.consg_code,
				consg_name = this.consg_name,
				supervisor = this.supervisor,
				tel = this.tel,
				fax = this.fax,
				email = this.email,
			};
		}
	}
}
