//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_vendor
    {
        public string corpcode { get; set; }
        public string chinesename { get; set; }
        public string englishname { get; set; }
        public string Representative { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Trans { get; set; }
        public string Location { get; set; }
        public string region { get; set; }
        public string shipper { get; set; }
        public string shipperTel { get; set; }
    }
}
