//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_newpacking
    {
        public string so_no { get; set; }
        public string newseq { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> qtybal { get; set; }
        public Nullable<int> pcs { get; set; }
        public Nullable<int> pcsbal { get; set; }
        public Nullable<int> qtyinplt { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<decimal> unitwei { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> spec { get; set; }
        public Nullable<System.DateTime> repackdate { get; set; }
        public string po { get; set; }
        public string item_no { get; set; }
        public string remark { get; set; }
        public Nullable<bool> LinkToIn { get; set; }
    }
}
