//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.AccountContInfo = new HashSet<AccountContInfo>();
            this.Truck_Account2 = new HashSet<Truck_Account2>();
            this.Customer_Order = new HashSet<Customer_Order>();
        }
    
        public string ClientCode { get; set; }
        public string Client1 { get; set; }
    
        public virtual ICollection<AccountContInfo> AccountContInfo { get; set; }
        public virtual ICollection<Truck_Account2> Truck_Account2 { get; set; }
        public virtual ICollection<Customer_Order> Customer_Order { get; set; }
    }
}
