//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalOut
    {
        public int id { get; set; }
        public System.DateTime operatedate { get; set; }
        public string so_no { get; set; }
        public string recline { get; set; }
        public string po { get; set; }
        public string skn { get; set; }
        public string sku { get; set; }
        public int ctns { get; set; }
        public Nullable<decimal> pcs { get; set; }
        public decimal cbm { get; set; }
        public string account { get; set; }
        public string Remark { get; set; }
    }
}
