//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingDtl
    {
        public int dID { get; set; }
        public Nullable<int> hID { get; set; }
        public string so_no { get; set; }
        public string orderNum { get; set; }
        public string po { get; set; }
        public string sku { get; set; }
        public string Marks { get; set; }
        public Nullable<int> CTN { get; set; }
        public Nullable<int> PCS { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string Remark { get; set; }
        public string ItemNo { get; set; }
        public string CustomerMaterialNo { get; set; }
        public string SalesMaterial { get; set; }
        public string Material { get; set; }
        public string SalesOrd { get; set; }
        public string Client { get; set; }
    }
}
