//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier_booking
    {
        public int cbID { get; set; }
        public string carrier { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string cont_size { get; set; }
        public Nullable<int> bookingNum { get; set; }
        public Nullable<int> releaseNum { get; set; }
        public string port { get; set; }
        public string dest { get; set; }
    }
}
