//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clp_chargeList
    {
        public int id { get; set; }
        public string clpno { get; set; }
        public string chargeCode { get; set; }
        public string remark { get; set; }
        public Nullable<int> ChargeTime { get; set; }
        public string Calculationmethod { get; set; }
        public string Calculationformula { get; set; }
        public string ActualFee { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
    }
}
