//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consignee
    {
        public string client { get; set; }
        public string consg_code { get; set; }
        public string consg_name { get; set; }
        public string supervisor { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
    }
}
