//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer1
    {
        public int id { get; set; }
        public string cust_name { get; set; }
        public string address1 { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string cust_email { get; set; }
        public string contact { get; set; }
        public string remark { get; set; }
        public string SM_Operator { get; set; }
        public string SM_email { get; set; }
    }
}
