//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string client { get; set; }
        public string cust_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string motion { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string sales_name { get; set; }
        public Nullable<decimal> cbm_price { get; set; }
        public Nullable<int> free_prd { get; set; }
        public string wght_unit { get; set; }
        public Nullable<decimal> stor_fee { get; set; }
        public Nullable<int> free_day { get; set; }
        public Nullable<decimal> hand_chrge { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
        public string remark { get; set; }
    }
}
