//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCR_Head
    {
        public int id { get; set; }
        public string fcr_no { get; set; }
        public string factory { get; set; }
        public string bl_no { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string discharging_port { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> docReceived_date { get; set; }
        public Nullable<System.DateTime> cargoReceived_date { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> last_modify_date { get; set; }
        public string creater_user { get; set; }
        public string last_modify_user { get; set; }
    }
}
