//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCR_Detail
    {
        public int id { get; set; }
        public string fcr_no { get; set; }
        public string seq { get; set; }
        public string clpno { get; set; }
        public string cfsso { get; set; }
        public string cont_no { get; set; }
        public string seal_no { get; set; }
    }
}
