//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class In2So
    {
        public int LinkID { get; set; }
        public string So_No { get; set; }
        public short LinkSeq { get; set; }
        public string pre_entry { get; set; }
        public string In_No { get; set; }
        public string g_no { get; set; }
        public string Seq { get; set; }
        public string NewSeq { get; set; }
        public string Item_No { get; set; }
        public Nullable<int> Pack_No { get; set; }
        public Nullable<int> PackBal { get; set; }
        public Nullable<int> Spec { get; set; }
        public Nullable<decimal> PCS { get; set; }
        public Nullable<decimal> PCSBal { get; set; }
        public string Remark { get; set; }
    }
}
