//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxId
    {
        public int id { get; set; }
        public string GroupValue { get; set; }
        public Nullable<int> Maxid1 { get; set; }
        public string Year { get; set; }
        public string Remark { get; set; }
        public string remark2 { get; set; }
    }
}
