//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class out_item_cy
    {
        public int ID { get; set; }
        public Nullable<int> aID { get; set; }
        public string so_no { get; set; }
        public string order_no { get; set; }
        public string po { get; set; }
        public string stock_no { get; set; }
        public string pattern_no { get; set; }
        public string pattern_name { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string destination { get; set; }
        public Nullable<int> pairage { get; set; }
        public Nullable<int> ctn { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string supplier { get; set; }
        public string commodity { get; set; }
        public string packing { get; set; }
        public string htsus_no { get; set; }
        public string line_no { get; set; }
        public string Material_Group_Desc { get; set; }
        public string ECV_Status { get; set; }
        public string Cases_Units_Status { get; set; }
    
        public virtual out_head_cy out_head_cy { get; set; }
    }
}
