//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class out_item
    {
        public string clpno { get; set; }
        public string oseq { get; set; }
        public string consg_code { get; set; }
        public string so_no { get; set; }
        public string seq { get; set; }
        public string LinkSeq { get; set; }
        public string g_no { get; set; }
        public string stk { get; set; }
        public string po { get; set; }
        public string sku { get; set; }
        public string pre_entry { get; set; }
        public string in_no { get; set; }
        public string case_no { get; set; }
        public string style_no { get; set; }
        public string item_no { get; set; }
        public string patterno { get; set; }
        public string pattern_name { get; set; }
        public string sample_no { get; set; }
        public string cat_code { get; set; }
        public string descr { get; set; }
        public Nullable<int> pallet { get; set; }
        public decimal qty { get; set; }
        public Nullable<int> ctns { get; set; }
        public Nullable<decimal> pcs { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> unitwei { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public string Location { get; set; }
        public string remark { get; set; }
        public string la_no { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public Nullable<bool> beloaded { get; set; }
        public string remark1 { get; set; }
        public string size { get; set; }
        public string NewSeq { get; set; }
        public Nullable<int> ScanQty { get; set; }
        public Nullable<bool> ScanFlag { get; set; }
        public Nullable<decimal> Act_Weight { get; set; }
    }
}
