//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutList
    {
        public decimal ebgID { get; set; }
        public string pre_entry { get; set; }
        public string g_no { get; set; }
        public string code_s { get; set; }
        public string code_t { get; set; }
        public string class_mark { get; set; }
        public string contr_item { get; set; }
        public string curr_code { get; set; }
        public string duty_mode { get; set; }
        public Nullable<decimal> factor { get; set; }
        public string g_name { get; set; }
        public decimal g_qty { get; set; }
        public string g_spec { get; set; }
        public string g_unit { get; set; }
        public string goods_id { get; set; }
        public decimal qty_1 { get; set; }
        public Nullable<decimal> qty_2 { get; set; }
        public string orign_coun { get; set; }
        public decimal trade_ttl { get; set; }
        public string unit_code1 { get; set; }
        public string unit_code2 { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<decimal> g_weight { get; set; }
        public Nullable<decimal> g_netwei { get; set; }
        public string exg_ver { get; set; }
        public string w_code_t { get; set; }
        public string w_code_s { get; set; }
        public string w_curr { get; set; }
        public Nullable<decimal> w_total { get; set; }
        public Nullable<short> pack_no { get; set; }
        public string CustomsDocuType { get; set; }
        public string ClpNo { get; set; }
    }
}
