//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck_Loading_Address
    {
        public string Loading_Whs { get; set; }
        public string Address { get; set; }
        public string TelNo { get; set; }
        public string Fax { get; set; }
        public string Contact_Name { get; set; }
        public string Email { get; set; }
    }
}
