//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck_Vendor
    {
        public string Vendor_Code { get; set; }
        public string Client { get; set; }
        public string Vendor_Name { get; set; }
        public string Vendor_Name2 { get; set; }
        public string Simple_Vendor_Name { get; set; }
        public string Address { get; set; }
        public string Simple_Address { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_TelNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contact_Person2 { get; set; }
        public string Contact_TelNo2 { get; set; }
        public string Email2 { get; set; }
        public string Contact_Person3 { get; set; }
        public string Contact_TelNo3 { get; set; }
        public string Email3 { get; set; }
        public string Status { get; set; }
    }
}
