//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck_Dest
    {
        public Truck_Dest()
        {
            this.Customer_Order = new HashSet<Customer_Order>();
        }
    
        public string DestCode { get; set; }
        public string Dest { get; set; }
    
        public virtual ICollection<Customer_Order> Customer_Order { get; set; }
    }
}
