//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.PocoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_Truck_Booking_Reg
    {
        public int ID { get; set; }
        public string SO_NO { get; set; }
        public Nullable<System.DateTime> Rec_BookingDate { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string VendorCode { get; set; }
    }
}
