//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class carrier_booking
	{
		public carrier_booking ToPOCO(bool isPOCO = true){
			return new carrier_booking(){
				cbID = this.cbID,
				carrier = this.carrier,
				vessel = this.vessel,
				voyage = this.voyage,
				ETD = this.ETD,
				cont_size = this.cont_size,
				bookingNum = this.bookingNum,
				releaseNum = this.releaseNum,
				port = this.port,
				dest = this.dest,
			};
		}
	}
}
