//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Models
{
	public partial class in_item
	{
		public in_item ToPOCO(bool isPOCO = true){
			return new in_item(){
				so_no = this.so_no,
				seq = this.seq,
				item_no = this.item_no,
				rec_date = this.rec_date,
				decldate = this.decldate,
				input_date = this.input_date,
				dest_port = this.dest_port,
				destination = this.destination,
				stk = this.stk,
				po = this.po,
				sku = this.sku,
				case_no = this.case_no,
				style_no = this.style_no,
				location = this.location,
				in_no = this.in_no,
				desc_code = this.desc_code,
				pallet = this.pallet,
				pltbal = this.pltbal,
				ctn = this.ctn,
				ctnbal = this.ctnbal,
				pcs = this.pcs,
				pcsbal = this.pcsbal,
				qty = this.qty,
				qtybal = this.qtybal,
				unit = this.unit,
				poqty = this.poqty,
				spec = this.spec,
				size = this.size,
				cbm = this.cbm,
				length = this.length,
				width = this.width,
				height = this.height,
				cubeunit = this.cubeunit,
				weight = this.weight,
				unitwei = this.unitwei,
				kgs_unit = this.kgs_unit,
				netwei = this.netwei,
				unitnetwei = this.unitnetwei,
				netwei_unit = this.netwei_unit,
				shuttle = this.shuttle,
				shuttle_fee = this.shuttle_fee,
				patterno = this.patterno,
				pattern_name = this.pattern_name,
				currency = this.currency,
				refund = this.refund,
				part = this.part,
				vessel = this.vessel,
				voyage = this.voyage,
				seal_no = this.seal_no,
				etd = this.etd,
				eta = this.eta,
				remark = this.remark,
				remark1 = this.remark1,
				remark2 = this.remark2,
				commodity = this.commodity,
				repacked = this.repacked,
				Prod_des = this.Prod_des,
				pcsperqty = this.pcsperqty,
				line = this.line,
				description = this.description,
				SI_Weight = this.SI_Weight,
				SI_WeightRemark = this.SI_WeightRemark,
			};
		}
	}
}
